### ISSUE TITLE
No manifest

### ISSUE THREAD

**Issue by billyboi2743** [Meowflow/school-bypasses#1]
There is no json manifest and therefore cannot be used.

**Comment by Meowflow** [comment]
Yo @billyboi2743 

Idk what you are talking about its just an html and therefore it cant be blocked. There is also a github pages but yea sorry i dont know what u mean

peace

**Comment by Meowflow** [comment]
It's been awhile.
Hi.
No json manifest is needed there's just pure HTML files you can run on a Chromebook or something.
