### ISSUE TITLE
ummmmm

### ISSUE THREAD

**Issue by soultoast3481** [Meowflow/school-bypasses#2]
sooooo... im kinda an idiot... how do i do this?

**Comment by Snipperrazer** [comment]
If you want too you can go to replit.com press login with google and fork the code and then upload from github

**Comment by Meowflow** [comment]
Hi,
Sorry for not replying, I don't really use GitHub that much anymore.
Just download the repository as a ZIP, extract it, and open any HTML (double-click it).

I recommend switching to my new website even though it looks garbage it works.

I am marking this as completed so if you need any further help you can open another issue. Thanks!
